spring:
  security:
    jwt:
      token:
        secret: FAS 
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 9n2016/a
    url: jdbc:postgresql://localhost/carritosrest
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties.hibernate.temp.use_jdbc_metadata_defaults: false